import type { Metadata } from 'next';
import './globals.css';
import ThemeProvider from '@/providers/ThemeProvider';
import { spaceGrotesk } from '@/lib/fonts';
import AosProvider from '@/providers/AosProvider';
import { Toaster } from 'sonner';
import { TChildren } from '@/types';

export const metadata: Metadata = {
  title: 'Aminul Islam',
  description: 'Generated by create next app',
};

const MainLayout = ({ children }: TChildren) => {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={spaceGrotesk.className} suppressHydrationWarning>
          <AosProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </AosProvider>
          <Toaster />
        </body>
      </html>
    </>
  );
};

export default MainLayout;
