import type { Metadata } from 'next';
import './globals.css';
import ThemeProvider from '@/providers/ThemeProvider';
import { spaceGrotesk } from '@/lib/fonts';
import AosProvider from '@/providers/AosProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const MainLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={spaceGrotesk.className} suppressHydrationWarning>
          <AosProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </AosProvider>
        </body>
      </html>
    </>
  );
};

export default MainLayout;
